---

- hosts: all
  become: true
  vars:
   packages_redhat:
    - httpd
    - php
    - firewalld

  tasks:

  - name: "Update repository, Install apache/php packge"
    apt:
     name: 
      - apache2
      - libapache2-mod-php
     state: latest
     update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: "Update reposirory, Install apache/php/firewalld packge"
    dnf:
     name: "{{ item }}"
     state: latest
     update_cache: yes
    with_items: "{{ packages_redhat }}"
    when: ansible_distribution == "RedHat"

